include: package:flutter_lints/flutter.yaml

analyzer:
  enable-experiment:
    - records
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    public_member_api_docs: false
