name: grafana_test_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

   # Auto-gen
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0

  # State management
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  provider: ^6.0.3

  # Service
  dio: ^5.0.2

  # Functional programming
  async: ^2.8.2
  dartz: ^0.10.1
  equatable: ^2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
